name: vanilla-component.js deploy to cdn.creco.me

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://npm.pkg.github.com"
      - name: check yarn
        run: |
          yarn -v
      - name: Execute build script
        run: ./scripts/build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CRECO_ORG_TOKEN }}
